#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprawy
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tikety")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSprawa(Sprawa instance);
    partial void UpdateSprawa(Sprawa instance);
    partial void DeleteSprawa(Sprawa instance);
    partial void InsertUzytkownik(Uzytkownik instance);
    partial void UpdateUzytkownik(Uzytkownik instance);
    partial void DeleteUzytkownik(Uzytkownik instance);
    partial void InsertWiadomosc(Wiadomosc instance);
    partial void UpdateWiadomosc(Wiadomosc instance);
    partial void DeleteWiadomosc(Wiadomosc instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TiketyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sprawa> Sprawas
		{
			get
			{
				return this.GetTable<Sprawa>();
			}
		}
		
		public System.Data.Linq.Table<Uzytkownik> Uzytkowniks
		{
			get
			{
				return this.GetTable<Uzytkownik>();
			}
		}
		
		public System.Data.Linq.Table<Wiadomosc> Wiadomoscs
		{
			get
			{
				return this.GetTable<Wiadomosc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sprawa")]
	public partial class Sprawa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSprawy;
		
		private string _Nazwa;
		
		private string _Opis;
		
		private System.Nullable<System.DateTime> _Termin;
		
		private System.DateTime _DataDodania;
		
		private System.Nullable<int> _IdUzytRealizuje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSprawyChanging(int value);
    partial void OnIdSprawyChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnOpisChanging(string value);
    partial void OnOpisChanged();
    partial void OnTerminChanging(System.Nullable<System.DateTime> value);
    partial void OnTerminChanged();
    partial void OnDataDodaniaChanging(System.DateTime value);
    partial void OnDataDodaniaChanged();
    partial void OnIdUzytRealizujeChanging(System.Nullable<int> value);
    partial void OnIdUzytRealizujeChanged();
    #endregion
		
		public Sprawa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSprawy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSprawy
		{
			get
			{
				return this._IdSprawy;
			}
			set
			{
				if ((this._IdSprawy != value))
				{
					this.OnIdSprawyChanging(value);
					this.SendPropertyChanging();
					this._IdSprawy = value;
					this.SendPropertyChanged("IdSprawy");
					this.OnIdSprawyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(50)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Opis", DbType="VarChar(MAX)")]
		public string Opis
		{
			get
			{
				return this._Opis;
			}
			set
			{
				if ((this._Opis != value))
				{
					this.OnOpisChanging(value);
					this.SendPropertyChanging();
					this._Opis = value;
					this.SendPropertyChanged("Opis");
					this.OnOpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataDodania", DbType="DateTime NOT NULL")]
		public System.DateTime DataDodania
		{
			get
			{
				return this._DataDodania;
			}
			set
			{
				if ((this._DataDodania != value))
				{
					this.OnDataDodaniaChanging(value);
					this.SendPropertyChanging();
					this._DataDodania = value;
					this.SendPropertyChanged("DataDodania");
					this.OnDataDodaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUzytRealizuje", DbType="Int")]
		public System.Nullable<int> IdUzytRealizuje
		{
			get
			{
				return this._IdUzytRealizuje;
			}
			set
			{
				if ((this._IdUzytRealizuje != value))
				{
					this.OnIdUzytRealizujeChanging(value);
					this.SendPropertyChanging();
					this._IdUzytRealizuje = value;
					this.SendPropertyChanged("IdUzytRealizuje");
					this.OnIdUzytRealizujeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uzytkownik")]
	public partial class Uzytkownik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDUzyt;
		
		private string _Nazwisko;
		
		private string _Imie;
		
		private string _email;
		
		private string _Telefon;
		
		private System.Nullable<bool> _Agent;
		
		private EntitySet<Wiadomosc> _Wiadomoscs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUzytChanging(int value);
    partial void OnIDUzytChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnAgentChanging(System.Nullable<bool> value);
    partial void OnAgentChanged();
    #endregion
		
		public Uzytkownik()
		{
			this._Wiadomoscs = new EntitySet<Wiadomosc>(new Action<Wiadomosc>(this.attach_Wiadomoscs), new Action<Wiadomosc>(this.detach_Wiadomoscs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUzyt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDUzyt
		{
			get
			{
				return this._IDUzyt;
			}
			set
			{
				if ((this._IDUzyt != value))
				{
					this.OnIDUzytChanging(value);
					this.SendPropertyChanging();
					this._IDUzyt = value;
					this.SendPropertyChanged("IDUzyt");
					this.OnIDUzytChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(50)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(50)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent", DbType="Bit")]
		public System.Nullable<bool> Agent
		{
			get
			{
				return this._Agent;
			}
			set
			{
				if ((this._Agent != value))
				{
					this.OnAgentChanging(value);
					this.SendPropertyChanging();
					this._Agent = value;
					this.SendPropertyChanged("Agent");
					this.OnAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzytkownik_Wiadomosc", Storage="_Wiadomoscs", ThisKey="IDUzyt", OtherKey="IdUzyt")]
		public EntitySet<Wiadomosc> Wiadomoscs
		{
			get
			{
				return this._Wiadomoscs;
			}
			set
			{
				this._Wiadomoscs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wiadomoscs(Wiadomosc entity)
		{
			this.SendPropertyChanging();
			entity.Uzytkownik = this;
		}
		
		private void detach_Wiadomoscs(Wiadomosc entity)
		{
			this.SendPropertyChanging();
			entity.Uzytkownik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wiadomosc")]
	public partial class Wiadomosc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdWiadomosci;
		
		private System.Nullable<int> _IdSprawy;
		
		private string _Tresc;
		
		private string _Zalacznik;
		
		private System.Nullable<int> _IdUzyt;
		
		private System.Nullable<System.DateTime> _Data;
		
		private EntityRef<Uzytkownik> _Uzytkownik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdWiadomosciChanging(int value);
    partial void OnIdWiadomosciChanged();
    partial void OnIdSprawyChanging(System.Nullable<int> value);
    partial void OnIdSprawyChanged();
    partial void OnTrescChanging(string value);
    partial void OnTrescChanged();
    partial void OnZalacznikChanging(string value);
    partial void OnZalacznikChanged();
    partial void OnIdUzytChanging(System.Nullable<int> value);
    partial void OnIdUzytChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    #endregion
		
		public Wiadomosc()
		{
			this._Uzytkownik = default(EntityRef<Uzytkownik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdWiadomosci", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdWiadomosci
		{
			get
			{
				return this._IdWiadomosci;
			}
			set
			{
				if ((this._IdWiadomosci != value))
				{
					this.OnIdWiadomosciChanging(value);
					this.SendPropertyChanging();
					this._IdWiadomosci = value;
					this.SendPropertyChanged("IdWiadomosci");
					this.OnIdWiadomosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSprawy", DbType="Int")]
		public System.Nullable<int> IdSprawy
		{
			get
			{
				return this._IdSprawy;
			}
			set
			{
				if ((this._IdSprawy != value))
				{
					this.OnIdSprawyChanging(value);
					this.SendPropertyChanging();
					this._IdSprawy = value;
					this.SendPropertyChanged("IdSprawy");
					this.OnIdSprawyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tresc", DbType="VarChar(MAX)")]
		public string Tresc
		{
			get
			{
				return this._Tresc;
			}
			set
			{
				if ((this._Tresc != value))
				{
					this.OnTrescChanging(value);
					this.SendPropertyChanging();
					this._Tresc = value;
					this.SendPropertyChanged("Tresc");
					this.OnTrescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zalacznik", DbType="VarChar(50)")]
		public string Zalacznik
		{
			get
			{
				return this._Zalacznik;
			}
			set
			{
				if ((this._Zalacznik != value))
				{
					this.OnZalacznikChanging(value);
					this.SendPropertyChanging();
					this._Zalacznik = value;
					this.SendPropertyChanged("Zalacznik");
					this.OnZalacznikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUzyt", DbType="Int")]
		public System.Nullable<int> IdUzyt
		{
			get
			{
				return this._IdUzyt;
			}
			set
			{
				if ((this._IdUzyt != value))
				{
					if (this._Uzytkownik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUzytChanging(value);
					this.SendPropertyChanging();
					this._IdUzyt = value;
					this.SendPropertyChanged("IdUzyt");
					this.OnIdUzytChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Uzytkownik_Wiadomosc", Storage="_Uzytkownik", ThisKey="IdUzyt", OtherKey="IDUzyt", IsForeignKey=true, DeleteRule="CASCADE")]
		public Uzytkownik Uzytkownik
		{
			get
			{
				return this._Uzytkownik.Entity;
			}
			set
			{
				Uzytkownik previousValue = this._Uzytkownik.Entity;
				if (((previousValue != value) 
							|| (this._Uzytkownik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Uzytkownik.Entity = null;
						previousValue.Wiadomoscs.Remove(this);
					}
					this._Uzytkownik.Entity = value;
					if ((value != null))
					{
						value.Wiadomoscs.Add(this);
						this._IdUzyt = value.IDUzyt;
					}
					else
					{
						this._IdUzyt = default(Nullable<int>);
					}
					this.SendPropertyChanged("Uzytkownik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
